# Generated by Django 5.2.17 on 2026-08-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinrecord",
            name="checkout_selfie_captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkinrecord",
            name="selfie_captured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
