# Generated by Django 5.2.17 on 2026-08-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_app", "0002_checkinrecord_checkout_selfie_captured_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinrecord",
            name="emergency_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkinrecord",
            name="is_emergency",
            field=models.BooleanField(default=False),
        ),
    ]
