# Generated by Django 5.2.17 on 2026-08-30 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_app", "0003_checkinrecord_emergency_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_adhoc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adhoc_job_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
