# Generated by Django 5.2.17 on 2026-08-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff_app", "0004_job_is_adhoc_job_requested_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="other_document",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents/other/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="passport_document",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents/passport/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="photo_document",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents/photo/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="visa_document",
            field=models.ImageField(blank=True, null=True, upload_to="documents/visa/"),
        ),
    ]
